### PR TITLE
provide a method to publicly access the foreign mapper class name string on relationships.

### PR DESCRIPTION
**Pull request by far-blue**
A small PR to add a public method giving access to the foreignMapperClass string. This will allow for easier creation of records and record sets of the correct foreign record type when creating empty records with relations.

### CODE REVIEW

**Comment by froschdesign** [comment]
Related to #21

**Comment by pmjones** [comment]
Sorry this took so long.

**Comment by far-blue** [comment]
Wonderful, thank you :)

**Comment by froschdesign** [comment]
@pmjones 
Unfortunately, this extension has not yet been released. What is the plan for it?

**Comment by pmjones** [comment]
@froschdesign @far-blue My apologies for the continued delay -- this, and #23 have been released in 1.4.0 as of a few minutes ago. Thank you for bringing it back to my attention, and for your patience!

**Comment by froschdesign** [comment]
@pmjones 
No problem at all. Thanks for the release! 👍🏻

**Pull request merged**
