### PR TITLE
Camel Case Support.

### PR DESCRIPTION
**Pull request by mcneely**
Added camel case support to records.
Update Tests.

### CODE REVIEW

**Comment by pmjones** [comment]
Hey @mcneely -- what's the motivation here?

**Comment by mcneely** [comment]
Just a nicety for us that prefer to use camel case over snake case. I know doctrine when generating classes automatically does the conversion.

**Comment by pmjones** [comment]
> prefer to use camel case over snake case

/me nods

So, what happens when the database table has both (e.g.) `fooId` and `foo_id` as columns? (Yes, I've seen this in the wild.)

Further, note that the purpose of Atlas is to help model the persistence system; as such, the property names should be those of the persistence system.

**Comment by pmjones** [comment]
@mcneely man, I'm sorry, but this introduces a level of "if not this then this instead" that rubs me the wrong way. Again, the purpose of Atlas is to be a model of persistence; dynamically changing property name addressing at this level just isn't suitable.

However, if your preference is very strong, it would be perfectly reasonable for you to create a custom base Record class of your own that overrides that method, then have your generated Record classes extend from that instead. (You can either do a search-and-replace on the existing classes, or write a Record template for the generator; cf. <http://atlasphp.io/cassini/skeleton/usage.html#1-2-1-4> and <https://github.com/atlasphp/Atlas.Cli/blob/2.x/resources/templates/TypeRecord.tpl>.)

**Comment by mcneely** [comment]
It's not worth maintaining my own fork for that and others have to reinvent same the wheel when they are in the same boat. It was a matter of convenience for other people as well as myself with very little change in the way of code..

**Comment by pmjones** [comment]
> not worth maintaining my own fork for that

I didn't mean to imply you need a fork for it; I'm saying that in the particular project where you use Atlas, you can modify the standard behavior any way you like.

Others, for example, may not want the camel-casing behavior; indeed, they might well consider that level of "flexibility" to be unexpected and erroneous.

**Pull request closed without merging**
